[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan migrate --force --isolated && php artisan serve --host=0.0.0.0 --port=$PORT"

