[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "./start.sh"

